### ISSUE TITLE
"This application is not opened" when sending a confirmation email

### ISSUE THREAD

**Issue by pyrog** [betaglop/e-venement#15]
When clicking on <img width="40" alt="send email button" src="https://cloud.githubusercontent.com/assets/2158081/13546590/ce2be4ea-e2b2-11e5-92f6-a2a1ec171de2.png"> from **operation**, open another "screen" and display *"This application is not opened"*

<img width="891" alt="send confirmation email" src="https://cloud.githubusercontent.com/assets/2158081/13546583/7ecd1536-e2b2-11e5-8331-60f4e042e571.png">

<img width="436" alt="Screen copy" src="https://cloud.githubusercontent.com/assets/2158081/13546655/6ff8c9fe-e2b4-11e5-8a50-ca9dfff5f337.png">

**Comment by pyrog** [comment]
Create the `apps/pub/config/app.yml` file and set open parameter to `true`.

```yaml
# default values
all:
  open: true

```
Note: if this file exist but open is set to `false`, the following message is displayed.
```yaml
  texts:
    when_closed:
      fr: La vente en ligne est actuellement fermée... Veuillez réessayer ultérieurement.
      en: The store is closed for the moment... Please try again later.

```
